In [73]:
import numpy as np
import pandas as pd
from matplotlib.pyplot import subplots
import statsmodels.api as sm
from ISLP import load_data
from ISLP.models import (ModelSpec as MS, summarize)

# default library imports

In [74]:
from ISLP import confusion_table
from ISLP.models import contrast
from sklearn.discriminant_analysis import (LinearDiscriminantAnalysis as LDA, QuadraticDiscriminantAnalysis as QDA)
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [75]:
Smarket = load_data("Smarket")
Smarket

Year   Lag1   Lag2   Lag3   Lag4   Lag5   Volume  Today Direction
0     2001  0.381 -0.192 -2.624 -1.055  5.010  1.19130  0.959        Up
1     2001  0.959  0.381 -0.192 -2.624 -1.055  1.29650  1.032        Up
2     2001  1.032  0.959  0.381 -0.192 -2.624  1.41120 -0.623      Down
3     2001 -0.623  1.032  0.959  0.381 -0.192  1.27600  0.614        Up
4     2001  0.614 -0.623  1.032  0.959  0.381  1.20570  0.213        Up
...    ...    ...    ...    ...    ...    ...      ...    ...       ...
1245  2005  0.422  0.252 -0.024 -0.584 -0.285  1.88850  0.043        Up
1246  2005  0.043  0.422  0.252 -0.024 -0.584  1.28581 -0.955      Down
1247  2005 -0.955  0.043  0.422  0.252 -0.024  1.54047  0.130        Up
1248  2005  0.130 -0.955  0.043  0.422  0.252  1.42236 -0.298      Down
1249  2005 -0.298  0.130 -0.955  0.043  0.422  1.38254 -0.489      Down

[1250 rows x 9 columns]

In [76]:
Smarket.columns

Index(['Year', 'Lag1', 'Lag2', 'Lag3', 'Lag4', 'Lag5', 'Volume', 'Today',
       'Direction'],
      dtype='object')

In [77]:
# Smarket.corr()

- Here the corr will return an error because there's a qualitative predictor - Direction.
- By that, I attempted to drop the "Direction" column and get the correlation matrix.

In [78]:
df = Smarket.drop(columns=["Direction"])
df.corr()

Year      Lag1      Lag2      Lag3      Lag4      Lag5    Volume  \
Year    1.000000  0.029700  0.030596  0.033195  0.035689  0.029788  0.539006   
Lag1    0.029700  1.000000 -0.026294 -0.010803 -0.002986 -0.005675  0.040910   
Lag2    0.030596 -0.026294  1.000000 -0.025897 -0.010854 -0.003558 -0.043383   
Lag3    0.033195 -0.010803 -0.025897  1.000000 -0.024051 -0.018808 -0.041824   
Lag4    0.035689 -0.002986 -0.010854 -0.024051  1.000000 -0.027084 -0.048414   
Lag5    0.029788 -0.005675 -0.003558 -0.018808 -0.027084  1.000000 -0.022002   
Volume  0.539006  0.040910 -0.043383 -0.041824 -0.048414 -0.022002  1.000000   
Today   0.030095 -0.026155 -0.010250 -0.002448 -0.006900 -0.034860  0.014592   

           Today  
Year    0.030095  
Lag1   -0.026155  
Lag2   -0.010250  
Lag3   -0.002448  
Lag4   -0.006900  
Lag5   -0.034860  
Volume  0.014592  
Today   1.000000

In [79]:
# Build the model 

allvars = Smarket.drop(columns=["Year" , "Today" , "Direction"])
X = MS(allvars).fit_transform(Smarket)
y = Smarket["Direction"] == "Up"
glm = sm.GLM(y , X , family = sm.families.Binomial())
result = glm.fit()
summarize(result)

coef  std err      z  P>|z|
intercept -0.1260    0.241 -0.523  0.601
Lag1      -0.0731    0.050 -1.457  0.145
Lag2      -0.0423    0.050 -0.845  0.398
Lag3       0.0111    0.050  0.222  0.824
Lag4       0.0094    0.050  0.187  0.851
Lag5       0.0103    0.050  0.208  0.835
Volume     0.1354    0.158  0.855  0.392

In [80]:
result.params

intercept   -0.126000
Lag1        -0.073074
Lag2        -0.042301
Lag3         0.011085
Lag4         0.009359
Lag5         0.010313
Volume       0.135441
dtype: float64

In [81]:
result.pvalues

intercept    0.600700
Lag1         0.145232
Lag2         0.398352
Lag3         0.824334
Lag4         0.851445
Lag5         0.834998
Volume       0.392404
dtype: float64

In [82]:
probs = result.predict()
probs[:10]

array([0.50708413, 0.48146788, 0.48113883, 0.51522236, 0.51078116,
       0.50695646, 0.49265087, 0.50922916, 0.51761353, 0.48883778])

In [83]:
labels = np.array(['Down'] * len(Smarket['Lag1']))
labels[probs > 0.5] = "Up"
labels

array(['Up', 'Down', 'Down', ..., 'Up', 'Up', 'Up'],
      shape=(1250,), dtype='<U4')

In [84]:
confusion_table(labels , Smarket['Direction'])

Truth      Down   Up
Predicted           
Down        145  141
Up          457  507

In [85]:
(145 + 507) / 1250 , np.mean(labels == Smarket['Direction'])

(0.5216, np.float64(0.5216))

In [86]:
train = (Smarket.Year < 2005)
Smarket_train = Smarket.loc[train]
Smarket_test = Smarket.loc[~train]
Smarket_test

Year   Lag1   Lag2   Lag3   Lag4   Lag5   Volume  Today Direction
998   2005 -0.134  0.008 -0.007  0.715 -0.431  0.78690 -0.812      Down
999   2005 -0.812 -0.134  0.008 -0.007  0.715  1.51080 -1.167      Down
1000  2005 -1.167 -0.812 -0.134  0.008 -0.007  1.72100 -0.363      Down
1001  2005 -0.363 -1.167 -0.812 -0.134  0.008  1.73890  0.351        Up
1002  2005  0.351 -0.363 -1.167 -0.812 -0.134  1.56910 -0.143      Down
...    ...    ...    ...    ...    ...    ...      ...    ...       ...
1245  2005  0.422  0.252 -0.024 -0.584 -0.285  1.88850  0.043        Up
1246  2005  0.043  0.422  0.252 -0.024 -0.584  1.28581 -0.955      Down
1247  2005 -0.955  0.043  0.422  0.252 -0.024  1.54047  0.130        Up
1248  2005  0.130 -0.955  0.043  0.422  0.252  1.42236 -0.298      Down
1249  2005 -0.298  0.130 -0.955  0.043  0.422  1.38254 -0.489      Down

[252 rows x 9 columns]

In [87]:
X_train = X.loc[train]
y_train = y.loc[train]
X_test = X.loc[~train]
y_test = y.loc[~train]

glm_train = sm.GLM(y_train , X_train , family = sm.families.Binomial())
result = glm_train.fit()
summarize(result)
probs = result.predict(exog=X_test)

X_test

intercept   Lag1   Lag2   Lag3   Lag4   Lag5   Volume
998         1.0 -0.134  0.008 -0.007  0.715 -0.431  0.78690
999         1.0 -0.812 -0.134  0.008 -0.007  0.715  1.51080
1000        1.0 -1.167 -0.812 -0.134  0.008 -0.007  1.72100
1001        1.0 -0.363 -1.167 -0.812 -0.134  0.008  1.73890
1002        1.0  0.351 -0.363 -1.167 -0.812 -0.134  1.56910
...         ...    ...    ...    ...    ...    ...      ...
1245        1.0  0.422  0.252 -0.024 -0.584 -0.285  1.88850
1246        1.0  0.043  0.422  0.252 -0.024 -0.584  1.28581
1247        1.0 -0.955  0.043  0.422  0.252 -0.024  1.54047
1248        1.0  0.130 -0.955  0.043  0.422  0.252  1.42236
1249        1.0 -0.298  0.130 -0.955  0.043  0.422  1.38254

[252 rows x 7 columns]

In [ ]:
D = Smarket.Direction
D_train , D_test = D.loc[train] , D.loc[~train]

(998     Down
 999     Down
 1000    Down
 1001      Up
 1002    Down
         ... 
 1245      Up
 1246    Down
 1247      Up
 1248    Down
 1249    Down
 Name: Direction, Length: 252, dtype: category
 Categories (2, object): ['Down', 'Up'],
 array(['Up', 'Up', 'Up', 'Up', 'Up', 'Up', 'Up', 'Up', 'Up', 'Up', 'Up',
        'Down', 'Up', 'Up', 'Up', 'Up', 'Up', 'Down', 'Up', 'Up', 'Down',
        'Down', 'Down', 'Up', 'Down', 'Down', 'Up', 'Up', 'Up', 'Down',
        'Down', 'Up', 'Up', 'Up', 'Up', 'Up', 'Up', 'Down', 'Down', 'Up',
        'Up', 'Up', 'Up', 'Down', 'Down', 'Up', 'Up', 'Up', 'Up', 'Up',
        'Up', 'Up', 'Up', 'Up', 'Up', 'Up', 'Up', 'Up', 'Up', 'Up', 'Down',
        'Down', 'Up', 'Up', 'Down', 'Down', 'Down', 'Up', 'Up', 'Up', 'Up',
        'Up', 'Up', 'Up', 'Down', 'Up', 'Down', 'Down', 'Up', 'Up', 'Up',
        'Up', 'Up', 'Down', 'Up', 'Down', 'Down', 'Up', 'Up', 'Up', 'Up',
        'Up', 'Up', 'Down', 'Down', 'Down', 'Down', 'Up', 'Up', 'Up', 'Up',
        'Up', 'D

In [142]:
labels = np.array(["Down"] * 252)
labels[probs > 0.5] = "Up"
confusion_table(labels , D_test)
D_test , labels

(998     Down
 999     Down
 1000    Down
 1001      Up
 1002    Down
         ... 
 1245      Up
 1246    Down
 1247      Up
 1248    Down
 1249    Down
 Name: Direction, Length: 252, dtype: category
 Categories (2, object): ['Down', 'Up'],
 array(['Up', 'Up', 'Up', 'Up', 'Up', 'Up', 'Up', 'Up', 'Up', 'Up', 'Up',
        'Down', 'Up', 'Up', 'Up', 'Up', 'Up', 'Down', 'Up', 'Up', 'Down',
        'Down', 'Down', 'Up', 'Down', 'Down', 'Up', 'Up', 'Up', 'Down',
        'Down', 'Up', 'Up', 'Up', 'Up', 'Up', 'Up', 'Down', 'Down', 'Up',
        'Up', 'Up', 'Up', 'Down', 'Down', 'Up', 'Up', 'Up', 'Up', 'Up',
        'Up', 'Up', 'Up', 'Up', 'Up', 'Up', 'Up', 'Up', 'Up', 'Up', 'Down',
        'Down', 'Up', 'Up', 'Down', 'Down', 'Down', 'Up', 'Up', 'Up', 'Up',
        'Up', 'Up', 'Up', 'Down', 'Up', 'Down', 'Down', 'Up', 'Up', 'Up',
        'Up', 'Up', 'Down', 'Up', 'Down', 'Down', 'Up', 'Up', 'Up', 'Up',
        'Up', 'Up', 'Down', 'Down', 'Down', 'Down', 'Up', 'Up', 'Up', 'Up',
        'Up', 'D

In [90]:
np.mean(labels == D_test) , np.mean(labels != D_test)

(np.float64(0.4801587301587302), np.float64(0.5198412698412699))

In [91]:
X = MS(['Lag1' , 'Lag2']).fit_transform(Smarket)

X_train = X.loc[train]
y_train = y.loc[train]
X_test = X.loc[~train]
y_test = y.loc[~train]

glm_train = sm.GLM(y_train , X_train , family = sm.families.Binomial())
result = glm_train.fit()
summarize(result)
probs = result.predict(exog=X_test)

In [92]:
D = Smarket.Direction
D_train , D_test = D.loc[train] , D.loc[~train]

In [93]:
labels = np.array(["Down"] * 252)
labels[probs > 0.5] = "Up"
confusion_table(labels , D_test)

Truth      Down   Up
Predicted           
Down         35   35
Up           76  106

In [94]:
np.mean(labels == D_test) , np.mean(labels != D_test)

(np.float64(0.5595238095238095), np.float64(0.44047619047619047))

In [95]:
X_test = pd.DataFrame({ 'Lag1' : [1.2 , 1.5],
                        'Lag2' : [1.1 , -0.8]})
model = MS(['Lag1' , 'Lag2']).fit(Smarket)
test_data = model.transform(X_test)
result.predict(test_data)


0    0.479146
1    0.496094
dtype: float64

In [96]:
lda = LDA(store_covariance=True)

In [97]:
train = Smarket.Year < 2005
X = MS(['Lag1' , 'Lag2']).fit_transform(Smarket)
X_train , X_test = X.loc[train] , X.loc[~train]

D = Smarket.Direction
D_train , D_test = D.loc[train] , D.loc[~train]

X_train , X_test = [M.drop(columns = ['intercept']) for M in [X_train , X_test]]
lda.fit(X_train , D_train)

LinearDiscriminantAnalysis(store_covariance=True)

In [98]:
lda.means_

array([[ 0.04279022,  0.03389409],
       [-0.03954635, -0.03132544]])

In [99]:
lda.classes_

array(['Down', 'Up'], dtype='<U4')

In [100]:
lda.priors_

array([0.49198397, 0.50801603])

In [101]:
lda.scalings_

array([[-0.64201904],
       [-0.51352928]])

In [102]:
lda_pred = lda.predict(X_test)
confusion_table(lda_pred , D_test)

Truth      Down   Up
Predicted           
Down         35   35
Up           76  106

In [103]:
lda_prob = lda.predict_proba(X_test)
np.all(
    np.where(lda_prob[:,1] >= 0.5, 'Up','Down') == lda_pred
)

np.True_

In [104]:
np.all(
    [lda.classes_[i] for i in np.argmax(lda_prob, 1)] == lda_pred
)

np.True_

In [105]:
qda = QDA(store_covariance=True)
qda.fit(X_train, D_train)

QuadraticDiscriminantAnalysis(store_covariance=True)

In [106]:
qda.means_ , qda.priors_

(array([[ 0.04279022,  0.03389409],
        [-0.03954635, -0.03132544]]),
 array([0.49198397, 0.50801603]))

In [107]:
qda.covariance_[0]

array([[ 1.50662277, -0.03924806],
       [-0.03924806,  1.53559498]])

In [108]:
qda_pred = qda.predict(X_test)
confusion_table(qda_pred , D_test)

Truth      Down   Up
Predicted           
Down         30   20
Up           81  121

In [109]:
np.mean(qda_pred == D_test)

np.float64(0.5992063492063492)

In [110]:
NB = GaussianNB()
NB.fit(X_train , D_train)

GaussianNB()

In [111]:
NB.classes_

array(['Down', 'Up'], dtype='<U4')

In [112]:
NB.class_prior_

array([0.49198397, 0.50801603])

In [113]:
NB.theta_

array([[ 0.04279022,  0.03389409],
       [-0.03954635, -0.03132544]])

In [114]:
NB.var_

array([[1.50355429, 1.53246749],
       [1.51401364, 1.48732877]])

In [115]:
X_train[D_train == "Down"].var(ddof=0)

Lag1    1.503554
Lag2    1.532467
dtype: float64

In [116]:
nb_labels = NB.predict(X_test)
confusion_table(nb_labels , D_test)

Truth      Down   Up
Predicted           
Down         29   20
Up           82  121

In [117]:
NB.predict_proba(X_test)[:5]

array([[0.4873288 , 0.5126712 ],
       [0.47623584, 0.52376416],
       [0.46529531, 0.53470469],
       [0.47484469, 0.52515531],
       [0.49020587, 0.50979413]])

In [118]:
knn1 = KNeighborsClassifier(n_neighbors=1)
knn1.fit(X_train , D_train)
knn1_pred = knn1.predict(X_test)
np.mean(knn1_pred == D_test)

np.float64(0.5)

In [119]:
confusion_table(knn1_pred , D_test)

Truth      Down  Up
Predicted          
Down         43  58
Up           68  83

In [120]:
knn3 = KNeighborsClassifier(n_neighbors=3)
knn3.fit(X_train , D_train)
knn3_pred = knn3.predict(X_test)
np.mean(knn3_pred == D_test)

np.float64(0.5317460317460317)

In [121]:
confusion_table(knn3_pred , D_test)

Truth      Down  Up
Predicted          
Down         48  55
Up           63  86

In [122]:
Caravan = load_data("Caravan")
Purchase = Caravan.Purchase
Purchase.value_counts()

Purchase
No     5474
Yes     348
Name: count, dtype: int64

In [123]:
feature_df = Caravan.drop(columns=['Purchase'])

In [124]:
scaler = StandardScaler(with_mean=True , with_std=True , copy=True)

In [125]:
scaler.fit(feature_df)

StandardScaler()

In [126]:
X_std = scaler.transform(feature_df)

In [127]:
feature_std = pd.DataFrame(X_std , columns=[feature_df.columns])
feature_std.std()

MOSTYPE     1.000086
MAANTHUI    1.000086
MGEMOMV     1.000086
MGEMLEEF    1.000086
MOSHOOFD    1.000086
              ...   
AZEILPL     1.000086
APLEZIER    1.000086
AFIETS      1.000086
AINBOED     1.000086
ABYSTAND    1.000086
Length: 85, dtype: float64

In [128]:
X_train , X_test , y_train , y_test = train_test_split(feature_std , Purchase , test_size=1000 , random_state=0)

In [129]:
knn1 = KNeighborsClassifier(n_neighbors=1)
knn1.fit(X_train , y_train)
knn1_pred = knn1.predict(X_test)
np.mean(knn1_pred != y_test) , np.mean(y_test != "No")

(np.float64(0.111), np.float64(0.067))

In [130]:
confusion_table(knn1_pred , y_test)

Truth       No  Yes
Predicted          
No         880   58
Yes         53    9

In [131]:
for K in range(1 , 6):
    knn = KNeighborsClassifier(n_neighbors=K)
    knn.fit(X_train , y_train)
    knn_pred = knn.predict(X_test)
    C = confusion_table(knn_pred , y_test)
    templ = ('K={0:d}: # predicted to rent: {1:>2},' +
            ' # who did rent {2:d}, accuracy {3:.1%}')

    rent_pred = C.loc['Yes'].sum()
    rent_real = C.loc['Yes' , 'Yes'].sum()
    accuracy = rent_real / rent_pred
    print(templ.format(K , rent_pred , rent_real , accuracy))

K=1: # predicted to rent: 62, # who did rent 9, accuracy 14.5%
K=2: # predicted to rent:  6, # who did rent 1, accuracy 16.7%
K=3: # predicted to rent: 20, # who did rent 3, accuracy 15.0%
K=4: # predicted to rent:  4, # who did rent 0, accuracy 0.0%
K=5: # predicted to rent:  7, # who did rent 1, accuracy 14.3%


In [132]:
logit = LogisticRegression(C = 1e10 , solver="liblinear")
logit.fit(X_train , y_train)
logit_pred = logit.predict_proba(X_test)
# print(logit_pred)
logit_labels = np.where(logit_pred[:,1] > 5 , "Yes" , "No")

confusion_table(logit_labels , y_test)

Truth       No  Yes
Predicted          
No         933   67
Yes          0    0

In [133]:
logit_labels = np.where(logit_pred[:,1] > 0.25 , "Yes" , "No")

confusion_table(logit_labels , y_test)

Truth       No  Yes
Predicted          
No         913   58
Yes         20    9

In [134]:
Bike = load_data("Bikeshare")

In [135]:
Bike.columns , Bike.shape

(Index(['season', 'mnth', 'day', 'hr', 'holiday', 'weekday', 'workingday',
        'weathersit', 'temp', 'atemp', 'hum', 'windspeed', 'casual',
        'registered', 'bikers'],
       dtype='object'),
 (8645, 15))

In [136]:
Bike

season mnth  day  hr  holiday  weekday  workingday weathersit  temp  \
0          1  Jan    1   0        0        6           0      clear  0.24   
1          1  Jan    1   1        0        6           0      clear  0.22   
2          1  Jan    1   2        0        6           0      clear  0.22   
3          1  Jan    1   3        0        6           0      clear  0.24   
4          1  Jan    1   4        0        6           0      clear  0.24   
...      ...  ...  ...  ..      ...      ...         ...        ...   ...   
8640       1  Dec  365  19        0        6           0      clear  0.42   
8641       1  Dec  365  20        0        6           0      clear  0.42   
8642       1  Dec  365  21        0        6           0      clear  0.40   
8643       1  Dec  365  22        0        6           0      clear  0.38   
8644       1  Dec  365  23        0        6           0      clear  0.36   

       atemp   hum  windspeed  casual  registered  bikers  
0     0.2879  0.81     0.0000       3          13      16  
1     0.2727  0.80     0.0000       8          32      40  
2     0.2727  0.80     0.0000       5          27      32  
3     0.2879  0.75     0.0000       3          10      13  
4     0.2879  0.75     0.0000       0           1       1  
...      ...   ...        ...     ...         ...     ...  
8640  0.4242  0.54     0.2239      19          73      92  
8641  0.4242  0.54     0.2239       8          63      71  
8642  0.4091  0.58     0.1940       2          50      52  
8643  0.3939  0.62     0.1343       2          36      38  
8644  0.3788  0.66     0.0000       4          27      31  

[8645 rows x 15 columns]

In [137]:
vars = ['mnth',
 'hr',
 'workingday',
 'temp',
 'weathersit']
X = MS(vars).fit_transform(Bike)
y = Bike["bikers"]
model = sm.OLS(y , X).fit()
summarize(model)

coef  std err       t  P>|t|
intercept                    -68.6317    5.307 -12.932  0.000
mnth[Feb]                      6.8452    4.287   1.597  0.110
mnth[March]                   16.5514    4.301   3.848  0.000
mnth[April]                   41.4249    4.972   8.331  0.000
mnth[May]                     72.5571    5.641  12.862  0.000
mnth[June]                    67.8187    6.544  10.364  0.000
mnth[July]                    45.3245    7.081   6.401  0.000
mnth[Aug]                     53.2430    6.640   8.019  0.000
mnth[Sept]                    66.6783    5.925  11.254  0.000
mnth[Oct]                     75.8343    4.950  15.319  0.000
mnth[Nov]                     60.3100    4.610  13.083  0.000
mnth[Dec]                     46.4577    4.271  10.878  0.000
hr[1]                        -14.5793    5.699  -2.558  0.011
hr[2]                        -21.5791    5.733  -3.764  0.000
hr[3]                        -31.1408    5.778  -5.389  0.000
hr[4]                        -36.9075    5.802  -6.361  0.000
hr[5]                        -24.1355    5.737  -4.207  0.000
hr[6]                         20.5997    5.704   3.612  0.000
hr[7]                        120.0931    5.693  21.095  0.000
hr[8]                        223.6619    5.690  39.310  0.000
hr[9]                        120.5819    5.693  21.182  0.000
hr[10]                        83.8013    5.705  14.689  0.000
hr[11]                       105.4234    5.722  18.424  0.000
hr[12]                       137.2837    5.740  23.916  0.000
hr[13]                       136.0359    5.760  23.617  0.000
hr[14]                       126.6361    5.776  21.923  0.000
hr[15]                       132.0865    5.780  22.852  0.000
hr[16]                       178.5206    5.772  30.927  0.000
hr[17]                       296.2670    5.749  51.537  0.000
hr[18]                       269.4409    5.736  46.976  0.000
hr[19]                       186.2558    5.714  32.596  0.000
hr[20]                       125.5492    5.704  22.012  0.000
hr[21]                        87.5537    5.693  15.378  0.000
hr[22]                        59.1226    5.689  10.392  0.000
hr[23]                        26.8376    5.688   4.719  0.000
workingday                     1.2696    1.784   0.711  0.477
temp                         157.2094   10.261  15.321  0.000
weathersit[cloudy/misty]     -12.8903    1.964  -6.562  0.000
weathersit[heavy rain/snow] -109.7446   76.667  -1.431  0.152
weathersit[light rain/snow]  -66.4944    2.965 -22.425  0.000

In [138]:
hr_encode = contrast('hr' , 'sum')
mnth_encode = contrast('hr' , 'sum')
vars = [mnth_encode,
 hr_encode,
 'workingday',
 'temp',
 'weathersit']
X2 = MS(vars).fit_transform(Bike)
model2 = sm.OLS(y , X2).fit()
summarize(model2)

coef       std err       t  P>|t|
intercept                    3.741320e+01  2.680000e+00  13.959  0.000
hr[0]                        5.355000e+13  2.450000e+13   2.190  0.029
hr[1]                       -7.482000e+13  2.760000e+13  -2.712  0.007
hr[2]                       -1.667000e+13  1.550000e+13  -1.073  0.283
hr[3]                       -5.722000e+13  2.460000e+13  -2.324  0.020
hr[4]                        5.096000e+13  4.710000e+13   1.082  0.279
hr[5]                       -2.662000e+14  3.210000e+14  -0.829  0.407
hr[6]                        2.274000e+14  3.270000e+14   0.696  0.486
hr[7]                        5.694000e+14  1.920000e+14   2.962  0.003
hr[8]                        1.067000e+14  2.760000e+14   0.386  0.699
hr[9]                       -3.301000e+13  3.400000e+14  -0.097  0.923
hr[10]                      -2.836000e+14  2.840000e+14  -1.000  0.317
hr[11]                       1.319000e+13  4.720000e+12   2.796  0.005
hr[12]                       4.879000e+12  5.000000e+12   0.975  0.329
hr[13]                      -1.912000e+13  2.200000e+13  -0.870  0.385
hr[14]                       2.893000e+13  2.340000e+14   0.123  0.902
hr[15]                       2.245000e+13  2.410000e+14   0.093  0.926
hr[16]                      -1.831000e+13  1.360000e+13  -1.347  0.178
hr[17]                       5.642000e+14  3.490000e+14   1.615  0.106
hr[18]                       3.468000e+14  3.970000e+14   0.873  0.383
hr[19]                       1.369000e+13  2.300000e+13   0.595  0.552
hr[20]                      -2.975000e+13  2.440000e+13  -1.217  0.224
hr[21]                      -3.563000e+13  2.760000e+13  -1.289  0.197
hr[22]                      -5.286000e+12  6.630000e+12  -0.798  0.425
hr[0]                       -5.355000e+13  2.450000e+13  -2.190  0.029
hr[1]                        7.482000e+13  2.760000e+13   2.712  0.007
hr[2]                        1.667000e+13  1.550000e+13   1.073  0.283
hr[3]                        5.722000e+13  2.460000e+13   2.324  0.020
hr[4]                       -5.096000e+13  4.710000e+13  -1.082  0.279
hr[5]                        2.662000e+14  3.210000e+14   0.829  0.407
hr[6]                       -2.274000e+14  3.270000e+14  -0.696  0.486
hr[7]                       -5.694000e+14  1.920000e+14  -2.962  0.003
hr[8]                       -1.067000e+14  2.760000e+14  -0.386  0.699
hr[9]                        3.301000e+13  3.400000e+14   0.097  0.923
hr[10]                       2.836000e+14  2.840000e+14   1.000  0.317
hr[11]                      -1.319000e+13  4.720000e+12  -2.796  0.005
hr[12]                      -4.879000e+12  5.000000e+12  -0.975  0.329
hr[13]                       1.912000e+13  2.200000e+13   0.870  0.385
hr[14]                      -2.893000e+13  2.340000e+14  -0.123  0.902
hr[15]                      -2.245000e+13  2.410000e+14  -0.093  0.926
hr[16]                       1.831000e+13  1.360000e+13   1.347  0.178
hr[17]                      -5.642000e+14  3.490000e+14  -1.615  0.106
hr[18]                      -3.468000e+14  3.970000e+14  -0.873  0.383
hr[19]                      -1.369000e+13  2.300000e+13  -0.595  0.552
hr[20]                       2.975000e+13  2.440000e+13   1.217  0.224
hr[21]                       3.563000e+13  2.760000e+13   1.289  0.197
hr[22]                       5.286000e+12  6.630000e+12   0.798  0.425
workingday                   8.390000e-02  1.838000e+00   0.046  0.964
temp                         2.334514e+02  4.428000e+00  52.718  0.000
weathersit[cloudy/misty]    -1.280060e+01  1.997000e+00  -6.409  0.000
weathersit[heavy rain/snow] -1.285905e+02  7.908000e+01  -1.626  0.104
weathersit[light rain/snow] -6.196320e+01  3.040000e+00 -20.382  0.000